# Generated by Django 3.0.6 on 2021-01-01 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mouchard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, max_length=250, null=True, verbose_name='Action effectuée dans le système')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('visibilite', models.IntegerField(default=1, verbose_name='Visibilité')),
            ],
            options={
                'verbose_name': 'Mouchard',
                'verbose_name_plural': 'Mouchards',
                'db_table': 'Mouchard',
                'ordering': ('-created',),
            },
        ),
    ]
