# Generated by Django 3.0.6 on 2021-01-05 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0004_compagnie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.ImageField(blank=True, default='avatars/avatar.jpg', upload_to='avatars', verbose_name='Avatar')),
                ('adresse', models.CharField(blank=True, max_length=250, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=250, verbose_name='Téléphone')),
                ('nationalite', models.CharField(blank=True, max_length=250, verbose_name='Nationalité')),
                ('quartier', models.CharField(blank=True, max_length=250, verbose_name='Quartier')),
                ('ville', models.CharField(blank=True, max_length=250, verbose_name='Ville')),
                ('code', models.CharField(blank=True, max_length=250, verbose_name='code de Réinitialisation')),
                ('connecte', models.CharField(choices=[('En ligne', 'En ligne'), ('Hors ligne', 'Hors ligne')], default='Hors ligne', max_length=250, verbose_name='En ligne ?')),
                ('visibilite', models.IntegerField(default=1, verbose_name='Visibilité')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('desactivated', models.DateTimeField(auto_now=True, verbose_name='Date de Désactivation')),
                ('added_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_added_by', to=settings.AUTH_USER_MODEL)),
                ('compagnie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Compagnie', verbose_name='Compagnie')),
                ('desactivated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_desactivated_by', to=settings.AUTH_USER_MODEL)),
                ('groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name="Droits d'accès")),
                ('poste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Poste', verbose_name='Poste')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Site', verbose_name='Site')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'Profile',
                'ordering': ('created',),
            },
        ),
    ]
