# Generated by Django 3.0.6 on 2021-01-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AddField(
            model_name='profile',
            name='statut',
            field=models.CharField(blank=True, max_length=250, verbose_name="Statut de l'employé"),
        ),
    ]
