# Generated by Django 3.0.6 on 2021-01-12 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_profile_matricule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='groupe',
        ),
    ]
