# Generated by Django 3.0.6 on 2021-01-12 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('website', '0009_remove_profile_groupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name="Droits d'accès"),
        ),
    ]
