# Generated by Django 3.0.6 on 2021-01-18 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0010_profile_groupe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heureArrivee', models.DateTimeField(max_length=250, verbose_name="Heure d'arrivée")),
                ('heureDepart', models.DateTimeField(blank=True, null=True, verbose_name='Heure de Départ')),
                ('debutPause', models.DateTimeField(blank=True, null=True, verbose_name='Début de la Pause')),
                ('finPause', models.DateTimeField(blank=True, null=True, verbose_name='Fin de la Pause')),
                ('visibilite', models.IntegerField(default=1, verbose_name='Visibilité')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('desactivated', models.DateTimeField(auto_now=True, verbose_name='Date de Désactivation')),
                ('added_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presence_added_by', to=settings.AUTH_USER_MODEL)),
                ('desactivated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presence_desactivated_by', to=settings.AUTH_USER_MODEL)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Profile', verbose_name='Employé Concerné')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Site', verbose_name='Site Affilié')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presence_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Presence',
                'verbose_name_plural': 'Presences',
                'db_table': 'Presence',
                'ordering': ('-created',),
            },
        ),
    ]
