# Generated by Django 3.0.6 on 2021-01-19 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0011_presence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=250, null=True, verbose_name='Libellé')),
                ('visibilite', models.IntegerField(default=1, verbose_name='Visibilité')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('desactivated', models.DateTimeField(auto_now=True, verbose_name='Date de Désactivation')),
                ('added_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modele_added_by', to=settings.AUTH_USER_MODEL)),
                ('desactivated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modele_desactivated_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modele_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modele',
                'verbose_name_plural': 'Modeles',
                'db_table': 'Modele',
                'ordering': ('created',),
            },
        ),
    ]
